data_cfg:
  dataset_name: CASIA-B
  dataset_root: CASIA-B-pkl
  num_workers: 1
  remove_no_gallery: false
  test_dataset_name: CASIA-B

evaluator_cfg:
  enable_float16: false
  restore_ckpt_strict: true
  restore_hint: 120000
  save_name: mymodel
  sampler:
    batch_size: 1
    sample_type: all_ordered
    type: InferenceSampler
  metric: euc # cos

loss_cfg:
  loss_term_weight: 1.0
  margin: 0.2
  type: TripletLoss
  log_prefix: triplet

model_cfg:
  model: MyModel
  backbone_cfg:
    in_channels: 1
    layers_cfg:
      - BC-32
      - BC-32
      - M
      - FC-64-2
      - FC-64-2
      - M
      - FC-128-3
      - FC-128-3
    type: Plain
  backbone_cfg1:
    in_channels: 1
    layers_cfg:
      - BC-32
      - BC-32
      - M
    type: Plain
  backbone_cfg2:
    in_channels: 32
    layers_cfg:
      - FC-128-2
      - FC-128-2

    type: Plain
  backbone_cfg3:
    in_channels: 128
    layers_cfg:
      - FC-128-3
      - FC-128-3
    type: Plain
  backbone_cfg2_1:
    in_channels: 32
    layers_cfg:
      - FC-128-2
      - FC-128-2

    type: Plain
  SeparateFCs:
    in_channels: 128
    out_channels: 128
    parts_num: 128
  SeparateFCs0:
    in_channels: 128
    out_channels: 128
    parts_num: 40
  bin_num:
    - 16
  channels: [32, 64, 128]
  class_num: 74

optimizer_cfg:
  lr: 0.0001
  momentum: 0.9
  solver: Adam
  weight_decay: 0.0

scheduler_cfg:
  gamma: 0.1
  milestones:
    - 100000
  scheduler: MultiStepLR

trainer_cfg:
  enable_float16: true
  log_iter: 100
  with_test: true
  restore_ckpt_strict: true
  restore_hint: 0
  save_iter: 1000
  save_name: mymodel
  sync_BN: true
  total_iter: 120000
  sampler:
    batch_shuffle: false
    batch_size:
      - 8
      - 16
    frames_num_fixed: 30
    frames_num_max: 50
    frames_num_min: 25
    frames_skip_num: 10
    sample_type: fixed_ordered
    type: TripletSampler
